# 4.3 Universal Functions: Fast Element-Wise Array Functions

Also called `ufunc`s, universal functions are functions that perform element-wise operations on data in ndarrays.  

AKA: fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

Many are simple element-wise transformations like taking the square-root of all values (`numpy.sqrt`) or exponentiation (`numpy.exp`). These are called **unary ufuncs**

There are also **binary ufuncs** that take two arrays and return a single array as the result. `numpy.add` and `numpy.maximum` are examples

## Unary

In [4]:
import numpy as np
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3)) # do this to make my rng match the example...

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

## Binary

In [5]:
x = rng.standard_normal(8)
y = rng.standard_normal(8)
x

array([-1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,  2.34740965,
        0.96849691, -0.75938718,  0.90219827])

In [ ]:
y

In [ ]:
# Compute the element-wise maximums of x and y
np.maximum(x, y)

## Return multiple arrays

Most ufuncs return a single array, some like `numpy.modf` (return fractional and integral parts of a floating-point array) return multiple

In [6]:
arr = rng.standard_normal(7) * 5
arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [7]:
# Notice the unpacking here
remainder, whole_part = np.modf(arr)
remainder

In [ ]:
whole_part

## Utilizing Out

Can also specify an output object using the `out` argument

In [8]:
# View array
arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [9]:
# Make placeholder
out = np.zeros_like(arr)
out

array([0., 0., 0., 0., 0., 0., 0.])

In [10]:
# Add one to arr (does NOT modify arr)
np.add(arr,1)

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

In [ ]:
arr

In [12]:
# Add one to arr (DOES modify arr)
np.add(arr, 1, out=arr)

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

In [13]:
arr

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

In [14]:
# Add one to arr and assign to out
np.add(arr, 1, out = out)

array([ 6.51459671, -6.10791367,  1.2090537 ,  4.24741966, -4.71800536,
        1.59156205, 10.62369966])

In [15]:
out

array([ 6.51459671, -6.10791367,  1.2090537 ,  4.24741966, -4.71800536,
        1.59156205, 10.62369966])

In [16]:
arr

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

## Unary Ufunc Examples

<img src="./myImages/table4.4_unaryUfunc.png" width = 600>

## Binary Ufunc

<img src="./myImages/table4.5_binaryUfunc.png" width = 600>