# 4.5 File Input and Output with Arrays

Not super important since we'll be using `pandas` mostly.

numpy has a binary format that can be accessed with `numpy.save` and `numpy.load`

You don't have to use a file extension with save - `.npy` will be appended automatically.

Can also use `numpy.savez` to save multiple items to an uncompressed archive and `numpy.savez_compressed` to do the same, but compress them.

In [7]:
import numpy as np
arr = np.arange(10)
np.save("/Users/hortowe/my_tool_repos/pydata-book/examples/ex_array", arr)


In [8]:
# Prints and doesn't assign
np.load("/Users/hortowe/my_tool_repos/pydata-book/examples/ex_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Assign
foo = np.load("/Users/hortowe/my_tool_repos/pydata-book/examples/ex_array.npy")
foo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Multiple arrays
np.savez("/Users/hortowe/my_tool_repos/pydata-book/examples/array_archive.npz", a=arr, b=arr)

# Loaded as a dict-like object
arch = np.load("/Users/hortowe/my_tool_repos/pydata-book/examples/array_archive.npz")
arch["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Save and compress
np.savez_compressed("/Users/hortowe/my_tool_repos/pydata-book/examples/arrays_compressed.npz", a=arr, b=arr)