# 4.2 Pseudorangom Number Generation

Utilize the `numpy.random` module to create arrays of values from various sample distributions.  

`numpy.random` is over an order of magnitude faster than built-in `random` module.  

Functions such as `numpy.random.standard_normal` use the default random number generator from `numpy.random`, but you can set your own seed for reproducibility.

In [1]:
import numpy as np
samples = np.random.standard_normal(size=(4, 4))
samples

array([[-0.02171966,  0.88701674, -0.45195276,  0.54827717],
       [-0.10701946, -0.27035744,  1.07017298, -0.67482697],
       [ 1.01120144,  0.21122719,  0.33958266, -0.01758755],
       [ 0.53935047,  0.71509264, -0.17347885, -0.10536782]])

In [2]:
# Set rng
rng = np.random.default_rng(seed=12345)

# Make data
data = rng.standard_normal((2, 3))
data

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

In [3]:
# Contrast with other
data2 = np.random.standard_normal((2,3))
data2

array([[ 0.31661882,  1.1310374 ,  0.49155837],
       [-1.31842798,  0.45613746,  1.87763507]])

In [4]:
# Also note how re-using rng is now different:
data3 = rng.standard_normal((2, 3))
data3

array([[-1.3677927 ,  0.6488928 ,  0.36105811],
       [-1.95286306,  2.34740965,  0.96849691]])

In [5]:
# Have to reset seed to make it match
rng = np.random.default_rng(seed=12345)
data4 = rng.standard_normal((2, 3))
data4

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

<img src="./myImages/table4.3_rngModules.png" width = 600>